export type CountryCurrency = { name: string; code: string; currency: string; currencyName: string };

export const africanCountries: CountryCurrency[] = [
  { name: "Algeria", code: "DZ", currency: "DZD", currencyName: "Algerian dinar" },
  { name: "Angola", code: "AO", currency: "AOA", currencyName: "Kwanza" },
  { name: "Benin", code: "BJ", currency: "XOF", currencyName: "West African CFA franc" },
  { name: "Botswana", code: "BW", currency: "BWP", currencyName: "Pula" },
  { name: "Burkina Faso", code: "BF", currency: "XOF", currencyName: "West African CFA franc" },
  { name: "Burundi", code: "BI", currency: "BIF", currencyName: "Burundian franc" },
  { name: "Cabo Verde", code: "CV", currency: "CVE", currencyName: "Cape Verdean escudo" },
  { name: "Cameroon", code: "CM", currency: "XAF", currencyName: "Central African CFA franc" },
  { name: "Central African Republic", code: "CF", currency: "XAF", currencyName: "Central African CFA franc" },
  { name: "Chad", code: "TD", currency: "XAF", currencyName: "Central African CFA franc" },
  { name: "Comoros", code: "KM", currency: "KMF", currencyName: "Comorian franc" },
  { name: "Congo (Congo-Brazzaville)", code: "CG", currency: "XAF", currencyName: "Central African CFA franc" },
  { name: "Congo (DRC)", code: "CD", currency: "CDF", currencyName: "Congolese franc" },
  { name: "Côte d’Ivoire", code: "CI", currency: "XOF", currencyName: "West African CFA franc" },
  { name: "Djibouti", code: "DJ", currency: "DJF", currencyName: "Djiboutian franc" },
  { name: "Egypt", code: "EG", currency: "EGP", currencyName: "Egyptian pound" },
  { name: "Equatorial Guinea", code: "GQ", currency: "XAF", currencyName: "Central African CFA franc" },
  { name: "Eritrea", code: "ER", currency: "ERN", currencyName: "Nakfa" },
  { name: "Eswatini", code: "SZ", currency: "SZL", currencyName: "Lilangeni" },
  { name: "Ethiopia", code: "ET", currency: "ETB", currencyName: "Birr" },
  { name: "Gabon", code: "GA", currency: "XAF", currencyName: "Central African CFA franc" },
  { name: "Gambia", code: "GM", currency: "GMD", currencyName: "Dalasi" },
  { name: "Ghana", code: "GH", currency: "GHS", currencyName: "Cedi" },
  { name: "Guinea", code: "GN", currency: "GNF", currencyName: "Guinean franc" },
  { name: "Guinea-Bissau", code: "GW", currency: "XOF", currencyName: "West African CFA franc" },
  { name: "Kenya", code: "KE", currency: "KES", currencyName: "Kenyan shilling" },
  { name: "Lesotho", code: "LS", currency: "LSL", currencyName: "Loti" },
  { name: "Liberia", code: "LR", currency: "LRD", currencyName: "Liberian dollar" },
  { name: "Libya", code: "LY", currency: "LYD", currencyName: "Libyan dinar" },
  { name: "Madagascar", code: "MG", currency: "MGA", currencyName: "Ariary" },
  { name: "Malawi", code: "MW", currency: "MWK", currencyName: "Kwacha" },
  { name: "Mali", code: "ML", currency: "XOF", currencyName: "West African CFA franc" },
  { name: "Mauritania", code: "MR", currency: "MRU", currencyName: "Ouguiya" },
  { name: "Mauritius", code: "MU", currency: "MUR", currencyName: "Mauritian rupee" },
  { name: "Morocco", code: "MA", currency: "MAD", currencyName: "Moroccan dirham" },
  { name: "Mozambique", code: "MZ", currency: "MZN", currencyName: "Metical" },
  { name: "Namibia", code: "NA", currency: "NAD", currencyName: "Namibian dollar" },
  { name: "Niger", code: "NE", currency: "XOF", currencyName: "West African CFA franc" },
  { name: "Nigeria", code: "NG", currency: "NGN", currencyName: "Naira" },
  { name: "Rwanda", code: "RW", currency: "RWF", currencyName: "Rwandan franc" },
  { name: "São Tomé and Príncipe", code: "ST", currency: "STN", currencyName: "Dobra" },
  { name: "Senegal", code: "SN", currency: "XOF", currencyName: "West African CFA franc" },
  { name: "Seychelles", code: "SC", currency: "SCR", currencyName: "Seychellois rupee" },
  { name: "Sierra Leone", code: "SL", currency: "SLE", currencyName: "Leone" },
  { name: "Somalia", code: "SO", currency: "SOS", currencyName: "Somali shilling" },
  { name: "South Africa", code: "ZA", currency: "ZAR", currencyName: "Rand" },
  { name: "South Sudan", code: "SS", currency: "SSP", currencyName: "South Sudanese pound" },
  { name: "Sudan", code: "SD", currency: "SDG", currencyName: "Sudanese pound" },
  { name: "Tanzania", code: "TZ", currency: "TZS", currencyName: "Tanzanian shilling" },
  { name: "Togo", code: "TG", currency: "XOF", currencyName: "West African CFA franc" },
  { name: "Tunisia", code: "TN", currency: "TND", currencyName: "Tunisian dinar" },
  { name: "Uganda", code: "UG", currency: "UGX", currencyName: "Ugandan shilling" },
  { name: "Zambia", code: "ZM", currency: "ZMW", currencyName: "Zambian kwacha" },
  { name: "Zimbabwe", code: "ZW", currency: "USD", currencyName: "US dollar" },
];

export const commonCurrencies = [
  { code: "USD", name: "US Dollar" },
  { code: "EUR", name: "Euro" },
  { code: "GBP", name: "Pound Sterling" },
];

export function findCountry(name: string) {
  return africanCountries.find((c) => c.name === name);
}
